[gsheets]
type = "service_account"
project_id = "audit-procurement"
private_key_id = "7d621e413e1facc435e8aade1a4220a4bbda96b4"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDS44xrvGuHt9jE
3cnXIZU6DsckPb86sGgfvQcFz1NoG5hfutkW4/zCIvef7+5yqKWNEbopLwiQb1a7
ySG7LIqaalJVBkLQKtnC5pXQt+4PrFAocJWwzzozSOHixevhypPUg6tt7Dhs86Kv
b75N8MlUpl9KpW0JEamUezRLc9HwUWHayW/UXTpuKqUjzf9e9shengiUTO06YDxE
IOBy7R1DWuQPpdr4ZqunlK3bh9e1t/XAGJDuapVexJTaFswvROMdkeygqt+4e60S
8oAe7iEk4+6XWC3ISSX2piSU8MszkUkEr36BbGxHyWGhO1DA5gfhWNsV0D2AmXjL
++QMtga5AgMBAAECggEADtgPeUHg+8OYEXtfCrKFc3m40Lc776CdI6bFiMYoI8rV
dd+MCk1v7CZT8cEMsqtmQ8C8rsttueTsYPluU2N2OhpDw1JWf5qUi2B5qSBZNGc3
mTEbiD995EA8Dh9KVDFTKIFAHtOiwSCBEgI2jfvl3/x59qIgQ6QnoJjvfGQhod2n
5ED4sOExId+XX/GkDFY4NeTbZ7fXrGjtfoagfrAohJ352hg8YIftiUiMjzSEaIMm
rT14NpdKxTeVKOJFPLtPUznN2QNIZH4lFpjT73op2QOxQzp6yWvoWbH2HBhC2621
WCtAvcA39+euW7Wo4o6EEsqkkGtNEuNDJ0CxP5mBkQKBgQDrN+Ux2jqhEYkFobZO
CjjUjXu6JjvNGhLJUyyGhOOynO+dXIo2aezIxbQ2RAIYWgMzhsiqap1+FSxhDU//
WnpHnkzMiss2ItWuHYz1u3rlwT+FEojkghWOWGUgHIhczGyipH+iTevdsa2myHHe
hEBXY8jB/0uZu6c3s6acfQ2BHQKBgQDlhWAqj946Z9tTD7c+A1DDQJCdT/mEq3OU
YTcAAoin7ezU7iZwLpAxEEQlQBzwMUbP2qECbPbqFgUQM5Xm6fXVywOUzWO4Bptr
aSohinU2N+HGT7cIruH4pWVESXA0BnBYIlT91MYbtEMBhrVS7O8E7/RbvANAsx0Y
KpmC0GElTQKBgCK8OF5qSaorer6YKOHRZJ8O3ayZpM8fAJM2cybSTQW9Yy0r00VB
0zO67mftFxodgMeFKfDwmZ1a5xjV7HBbHh+hYtn5zRSLhF6YAo7vRrDTHtw55nlI
NIK2zwg07nY1wf0qqaaAN0qfyHMOurIPeajuFWGAn9tt+L2jDAGj/fCJAoGBAJ1B
6CThU+sCk7RydSOpE+Hjz/HpBNYQvu0wOoXoNoeQrg8qaO2+CY+ETJyVM/6iVJk/
e8f0rqyuj6ONJK0FKinkojyHCUbiSAStFm/KtQqD+U5t+cOaRzuc3yiNhLIwozLP
uxn7eg0rUimuiXga3J2uZuefhz8COfH/5hRJ//WVAoGAVS4hFnRklmh9jxBf0gNg
90NvtPky2i2HMRPq8BM6eD+CanrXkOgnLJM04VyGrBKXkCOtpCnpAflmpu7WfnSa
5tBtTBYBrjbqh5ybfOqW82HM54JTz+D17w/C0/1UspU+oiVPpFD+doTMekHIoaMe
jR7LbxBmyrGq4ZOLMCegujI=
-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheet-access@audit-procurement.iam.gserviceaccount.com"
client_id = "104213023278817461958"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheet-access@audit-procurement.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
