[gsheets]
type = "service_account"
project_id = "kitchen-orders-408920"
private_key_id = "exampleprivatekeyid123456789"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrWsQmcesCIs5/
VpCtgm1wOO+CntA2AU2oMMTAOzc47rVXZ9/PCuUJqvKF8ALegXyPZM9izSc0cdlJ
YO82rX1cUpKM8e3M4RXhBWJNaOaU/kAwFBW7oeVBnZs7T8Q6JsfkbcrUqv9oiUkL
+eVNrooICTIRJL+q2bkjQegmWZwWcdctJsakidpAzgyCiy5ej8SaI6ame+1t0eIA
R9Ile/jZn2fioA8mT5zayRUZXWImh9+4lRWBLXlW3O3ZjNsicxswat+iqOm1Eqz6
inO8J+SQhK4wtDwOww7OVJFsshZWBxt+J+psd3Od/nvViEK7RkaokAU+Rwk3UT+H
mw27Weu9AgMBAAECggEAEEw4DZujKXC/D2x5b6jqmMeWVc5q6XmmD07hv8Wodgrg
oF+ziuEzfjM0qvMnirTQVvq7IN+rXWxNdhKF3gwrn4OfbbY3xgp+7SHFqXnGbwbG
ex9fhWYCEWoYnbamzr/pt9SOrwiIKPZGkzpUij1rr0guODEBfxIDO/lX4VUZKMDJ
fNfW0EgPeqR5RIflk/2iKE481PcQ8/JTWaVmHx0wqs8ed1FdHqmCW2OpftQBoYLK
ZBlOnm9amfHmIgMvHL6uyh7hJDYkk/X3kRvhnUjX03KomIHbmznDuf4JHvLzELdD
jmvKiZupP3sjxBO7HE6gn761Bh28J4H+94nU8wr6nwKBgQDTJLrXuba9gO2RUEyQ
6vEoWQWsOLlyD1gxhanAzwwInanJi5/oXatBrojJcW4jrn6XNGn86ImvbPpsiEol
dYzwFe7dJsHIAeXlSyrEMc7a4TdaKm5H3LZ0Fr6w57asY2z4nNUbf4rOMLo2Z3Fa
hv7lgBYSPiN+4m6IHPw3yxsuGwKBgQDPwhJ5C9mS/ke53Uj7Dd94RpJFD4E1g1P+
5hDx+exPiFARQnoQwtd+0kqNICuUzQZsu2UYEqvi3RATuOyMZzl3/W7WCef+mf9Q
jyT1iXdv7aJdjMuEJ2FpRmlABxvROicQaFnBQN7509fMzJ+6LxtJKHiSEAv88n8z
kJXar+mLBwKBgGkMVyFJNo/l+0xW5SEcosruL5JVzn3fAIPy+lgBKv2GY5jwrKhR
IglVqpx+oMuD31ufKjQ4BXiQAa/JxwoICAzS/Lpus+6scxK3aRmfpkjj0EQ95AxA
1U3AmzMstYfjF65BaQ17UTXwrFSw9oaRr3PDXDfLTqGsSk3SDfI8TNONAoGAHu8I
jRlklexihZwbJ7ZTFbd8Q+ghFvSs5wEeeMj7lIP5V/iL8D7ykyGAlC68DnXQhRQJ
42G0Uh0ULbuVDPq5pdIIVLo43sHTMA2ANUb4j6PUTxWNn+m1KVWgijYEwExmUJ0Y
8BtWl+Ag+49kIPaum1/5Q9Y70rfQlL7scRlMLrUCgYEAjE10uHV/A3DjNZjjfB0z
NdKGEmhykT6igtFmZ1UYwQ1r0Xgh7c6hgRZ5HhD2W9fVx38Vpn6kLtZLWRF+uXrY
zxJjskmjBHsblRQSXLH14YJoBwGU8QUrc9BtqCnctoAAKR0g2J5Gf+MOe4FJhBWT
DJPmfsR08+iIho8adWqDYqU=
-----END PRIVATE KEY-----"""
client_email = "streamlit-kitchen-service@kitchen-orders-408920.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-kitchen-service%40kitchen-orders-408920.iam.gserviceaccount.com"
